In [2]:
from sklearn.ensemble import IsolationForest
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_digits


In [15]:
digits = load_digits()
# X = les données, y = les données attendues
X = digits.data ; y = digits.target

X

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [16]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [19]:
images = digits.images

In [17]:
images

array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0.,  0.],
        [ 0.,  0.,  3., ..., 14.,  0.,  0.],
        [ 0.,  0.,  8., ..., 16.,  0.,  0.],
        ...,
        [ 0.,  9., 16., ...,  0.,  0.,  0.],
        [ 0.,  3., 13., ..., 11.,  5.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.]],

       ...,

       [[ 0.,  0.,  1., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ...,  2.,  1.,  0.],
        [ 0.,  0., 16., ..., 16.,  5.,  0.

In [ ]:
model = IsolationForest(random_state=0,
contamination=0.02)
model.fit(X)

# Predict est un tableau de 1 et -1 (anomalies)
anomalies = np.where(model.predict(X)==-1)
plt.imshow(images[anomalies][0])
plt.title(y[anomalies][0])

0    1     2     3     4     5     6     7    8     9   ...    54   55  \
0   0.0  0.0   0.0   0.0  11.0  15.0   4.0   0.0  0.0   0.0  ...   0.0  0.0   
1   0.0  6.0  16.0  16.0  16.0  15.0  10.0   0.0  0.0   9.0  ...   0.0  0.0   
2   0.0  4.0  16.0  16.0  16.0  16.0   5.0   0.0  0.0  11.0  ...   0.0  0.0   
3   0.0  0.0   5.0  16.0  16.0  16.0  16.0  11.0  0.0   0.0  ...   0.0  0.0   
4   0.0  0.0   2.0  10.0  10.0  12.0  15.0  10.0  0.0   0.0  ...   0.0  0.0   
5   0.0  0.0   0.0  10.0  12.0  15.0  16.0  13.0  0.0   0.0  ...   0.0  0.0   
6   0.0  0.0   2.0  13.0  16.0  16.0  16.0  12.0  0.0   0.0  ...   0.0  0.0   
7   0.0  0.0   1.0   7.0  12.0   3.0   0.0   0.0  0.0   4.0  ...  14.0  5.0   
8   0.0  0.0   0.0   4.0  11.0  15.0  16.0  12.0  0.0   0.0  ...   0.0  0.0   
9   0.0  0.0   0.0   4.0  13.0  16.0  15.0   2.0  0.0   0.0  ...   0.0  0.0   
10  0.0  0.0   0.0   6.0  13.0  16.0  16.0   9.0  0.0   0.0  ...   0.0  0.0   
11  0.0  0.0   0.0  10.0   6.0   0.0  10.0  14.0  0.0   0.0  ...   0.0  0.0   
12  0.0  3.0  10.0  16.0  16.0  16.0   2.0   0.0  0.0  14.0  ...   0.0  0.0   
13  0.0  0.0   0.0   1.0   9.0  16.0   9.0   0.0  0.0   0.0  ...   0.0  0.0   
14  0.0  3.0  16.0  16.0  16.0   2.0   0.0   0.0  0.0   4.0  ...  16.0  0.0   
15  0.0  0.0   0.0   4.0  15.0   2.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
16  0.0  0.0   0.0   1.0  15.0   3.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
17  0.0  0.0   0.0   9.0  13.0   0.0   6.0   8.0  0.0   0.0  ...   0.0  0.0   
18  0.0  0.0  11.0  14.0   5.0   0.0   0.0   0.0  0.0   6.0  ...  15.0  0.0   
19  0.0  0.0   0.0   3.0  16.0   5.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
20  0.0  2.0   0.0   8.0   9.0   0.0   0.0   0.0  0.0  13.0  ...  13.0  0.0   
21  0.0  7.0  16.0  16.0  16.0  16.0  11.0   0.0  0.0   8.0  ...   0.0  0.0   
22  0.0  4.0   7.0  13.0  16.0  16.0   4.0   0.0  0.0  11.0  ...   0.0  0.0   
23  0.0  0.0  13.0  13.0   1.0   0.0   0.0   0.0  0.0   7.0  ...  15.0  1.0   
24  0.0  5.0  16.0  16.0  16.0  16.0  10.0   0.0  0.0   4.0  ...   0.0  0.0   
25  0.0  0.0   0.0   1.0  16.0   3.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
26  0.0  0.0   0.0   0.0   6.0  16.0   7.0   0.0  0.0   1.0  ...   9.0  0.0   
27  0.0  0.0   0.0   7.0  12.0  16.0  16.0  15.0  0.0   0.0  ...   0.0  0.0   
28  0.0  8.0  13.0  15.0  16.0  16.0   8.0   0.0  0.0   9.0  ...   0.0  0.0   
29  0.0  4.0  16.0  16.0  16.0  15.0   3.0   0.0  0.0  11.0  ...   0.0  0.0   
30  0.0  2.0  15.0  16.0   5.0   0.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
31  0.0  4.0  15.0  16.0  15.0   4.0   0.0   0.0  0.0  11.0  ...   0.0  0.0   
32  0.0  7.0  12.0  14.0  16.0   8.0   0.0   0.0  0.0   8.0  ...   0.0  0.0   
33  0.0  0.0   0.0   0.0   8.0  10.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
34  0.0  0.0   0.0   1.0  15.0   2.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   
35  0.0  0.0   0.0   0.0  13.0   8.0   0.0   0.0  0.0   0.0  ...   0.0  0.0   

     56   57    58    59    60    61    62   63  
0   0.0  0.0   0.0   1.0  11.0  16.0  12.0  0.0  
1   0.0  9.0  16.0  11.0   0.0   0.0   0.0  0.0  
2   0.0  4.0  16.0  12.0   1.0   0.0   0.0  0.0  
3   0.0  0.0   3.0  16.0   2.0   0.0   0.0  0.0  
4   0.0  0.0   0.0  14.0   2.0   0.0   0.0  0.0  
5   0.0  0.0   0.0  14.0   6.0   0.0   0.0  0.0  
6   0.0  0.0   3.0  15.0   4.0   0.0   0.0  0.0  
7   0.0  0.0   1.0   9.0  15.0  16.0  16.0  8.0  
8   0.0  0.0   0.0   5.0  10.0   0.0   0.0  0.0  
9   0.0  0.0   0.0   4.0  10.0   0.0   0.0  0.0  
10  0.0  0.0   0.0   7.0   9.0   0.0   0.0  0.0  
11  0.0  0.0   0.0  15.0   3.0   0.0   0.0  0.0  
12  0.0  2.0  15.0  16.0   8.0   0.0   0.0  0.0  
13  0.0  0.0   0.0   0.0  12.0   6.0   0.0  0.0  
14  0.0  3.0  13.0  15.0  16.0  16.0   8.0  0.0  
15  0.0  0.0   0.0   7.0  16.0   6.0   0.0  0.0  
16  0.0  0.0   0.0   2.0  16.0   6.0   0.0  0.0  
17  0.0  0.0   0.0  12.0  11.0   0.0   0.0  0.0  
18  0.0  0.0  11.0   8.0   4.0   5.0  16.0  1.0  
19  0.0  0.0   0.0   5.0  15.0   2.0   0.0  0.0  
20  0.0  0.0   0.0   9.0  16.0 